name: 'Passing secrets across envs'

on:
  workflow_dispatch:

jobs:
  download_prod_creds:
    runs-on: ubuntu-latest
    environment: 'prod'
    outputs:
      output2: ${{steps.create_Prod_secret_variable.outputs.csp}}

    steps:
      - id: Check_Out_Repository
        uses: actions/checkout@v2

      - id: create_Prod_secret_variable
        run: |
          #echo "${{secrets.AZURE_CERTIFICATE}}"
          #echo "::set-output name=csp::$(echo -n '${{secrets.AZURE_CERTIFICATE}}' | base64 | base64)"
          #echo "::set-output name=csp::(echo -n '${{secrets.AZURE_CERTIFICATE}}')"
          echo "::set-output name=orig_encoded_token::$(echo -n '${{secrets.AZURE_CERTIFICATE}}' | base64 | base64)"

  dev_promote_model:
    runs-on: ubuntu-latest
    needs : download_prod_creds
    environment: 'dev'

    steps:
      - id: Check_Out_Repository
        uses: actions/checkout@v2
  
      - id: Retrieve_prod_vars
        run: |
          echo "token_in_other_job=$(echo -n ${orig_encoded_token} | base64 --decode | base64 --decode)" >> $GITHUB_ENV
          #echo "token_in_other_job=$(echo -n ${csp} | base64 --decode | base64 --decode)" 
          #vars=${{needs.download_prod_creds.outputs.output2}}
          #echo "token_in_other_job=$(echo -n ${vars} | base64 --decode | base64 --decode)" 
          echo $token_in_other_job
