name: 'Passing secrets across envs'

on:
workflow_dispatch:

jobs:
download_prod_creds:
runs-on: ubuntu-latest
environment: 'Prod'
outputs:
output2: ${{steps.create_Prod_secret_variable.outputs.csp}}

steps:
- id: Check_Out_Repository
uses: actions/checkout@v2

- id: create_Prod_secret_variable
run: |
##${{secrets.AZURE_CERTIFICATE}}
echo "::set-output name=csp::(echo -n '${{secrets.AZURE_CERTIFICATE}}')"


dev_promote_model:
runs-on: ubuntu-latest
needs : download_prod_creds
environment: 'DEV'

steps:
- id: Check_Out_Repository
uses: actions/checkout@v2

- id: Retrieve_prod_vars
run: |
vars=${{needs.download_prod_creds.outputs.output2}}
echo $vars

