name: 'Passing secrets across envs'

on:
  workflow_dispatch:

jobs:
  download_prod_creds:
    runs-on: ubuntu-latest
    environment: 'prod'
    outputs:
      output2: ${{steps.create_Prod_secret_variable.outputs.orig_encoded_token}}

    steps:
      - id: Check_Out_Repository
        uses: actions/checkout@v2

      - id: create_Prod_secret_variable
        run: |
          echo "::set-output name=orig_encoded_token::$(echo -n '${{secrets.AZURE_CERTIFICATE}}' | base64 -w 0  | base64 -w 0 )"
          echo "${{steps.create_Prod_secret_variable.outputs.orig_encoded_token}}"
          echo -n '${{secrets.AZURE_CERTIFICATE}}' | base64 -w 0  | base64 -w 0

  dev_promote_model:
    runs-on: ubuntu-latest
    needs : download_prod_creds
    environment: 'dev'

    steps:
      - id: Check_Out_Repository
        uses: actions/checkout@v2
  
      - id: Retrieve_prod_vars
        run: |
          vars=${{needs.download_prod_creds.outputs.output2}}
          echo "token_in_other_job=$(echo -n ${vars} | base64 --ignore-garbage --decode | base64 --ignore-garbage --decode  )" 
          echo vars
          echo $token_in_other_job
          
